/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DataRouteImport } from './routes/data'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SppgIndexRouteImport } from './routes/sppg/index'
import { Route as SppgProfilRouteImport } from './routes/sppg/profil'
import { Route as SppgProduksiRouteImport } from './routes/sppg/produksi'
import { Route as SppgPengirimanRouteImport } from './routes/sppg/pengiriman'
import { Route as SppgKeuanganRouteImport } from './routes/sppg/keuangan'
import { Route as RegisterTokenRouteImport } from './routes/register/$token'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SppgIndexRoute = SppgIndexRouteImport.update({
  id: '/sppg/',
  path: '/sppg/',
  getParentRoute: () => rootRouteImport,
} as any)
const SppgProfilRoute = SppgProfilRouteImport.update({
  id: '/sppg/profil',
  path: '/sppg/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SppgProduksiRoute = SppgProduksiRouteImport.update({
  id: '/sppg/produksi',
  path: '/sppg/produksi',
  getParentRoute: () => rootRouteImport,
} as any)
const SppgPengirimanRoute = SppgPengirimanRouteImport.update({
  id: '/sppg/pengiriman',
  path: '/sppg/pengiriman',
  getParentRoute: () => rootRouteImport,
} as any)
const SppgKeuanganRoute = SppgKeuanganRouteImport.update({
  id: '/sppg/keuangan',
  path: '/sppg/keuangan',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTokenRoute = RegisterTokenRouteImport.update({
  id: '/register/$token',
  path: '/register/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/driver': typeof DriverRoute
  '/login': typeof LoginRoute
  '/register/$token': typeof RegisterTokenRoute
  '/sppg/keuangan': typeof SppgKeuanganRoute
  '/sppg/pengiriman': typeof SppgPengirimanRoute
  '/sppg/produksi': typeof SppgProduksiRoute
  '/sppg/profil': typeof SppgProfilRoute
  '/sppg/': typeof SppgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/driver': typeof DriverRoute
  '/login': typeof LoginRoute
  '/register/$token': typeof RegisterTokenRoute
  '/sppg/keuangan': typeof SppgKeuanganRoute
  '/sppg/pengiriman': typeof SppgPengirimanRoute
  '/sppg/produksi': typeof SppgProduksiRoute
  '/sppg/profil': typeof SppgProfilRoute
  '/sppg': typeof SppgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/driver': typeof DriverRoute
  '/login': typeof LoginRoute
  '/register/$token': typeof RegisterTokenRoute
  '/sppg/keuangan': typeof SppgKeuanganRoute
  '/sppg/pengiriman': typeof SppgPengirimanRoute
  '/sppg/produksi': typeof SppgProduksiRoute
  '/sppg/profil': typeof SppgProfilRoute
  '/sppg/': typeof SppgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/data'
    | '/driver'
    | '/login'
    | '/register/$token'
    | '/sppg/keuangan'
    | '/sppg/pengiriman'
    | '/sppg/produksi'
    | '/sppg/profil'
    | '/sppg/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/data'
    | '/driver'
    | '/login'
    | '/register/$token'
    | '/sppg/keuangan'
    | '/sppg/pengiriman'
    | '/sppg/produksi'
    | '/sppg/profil'
    | '/sppg'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/data'
    | '/driver'
    | '/login'
    | '/register/$token'
    | '/sppg/keuangan'
    | '/sppg/pengiriman'
    | '/sppg/produksi'
    | '/sppg/profil'
    | '/sppg/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  DataRoute: typeof DataRoute
  DriverRoute: typeof DriverRoute
  LoginRoute: typeof LoginRoute
  RegisterTokenRoute: typeof RegisterTokenRoute
  SppgKeuanganRoute: typeof SppgKeuanganRoute
  SppgPengirimanRoute: typeof SppgPengirimanRoute
  SppgProduksiRoute: typeof SppgProduksiRoute
  SppgProfilRoute: typeof SppgProfilRoute
  SppgIndexRoute: typeof SppgIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sppg/': {
      id: '/sppg/'
      path: '/sppg'
      fullPath: '/sppg/'
      preLoaderRoute: typeof SppgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sppg/profil': {
      id: '/sppg/profil'
      path: '/sppg/profil'
      fullPath: '/sppg/profil'
      preLoaderRoute: typeof SppgProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sppg/produksi': {
      id: '/sppg/produksi'
      path: '/sppg/produksi'
      fullPath: '/sppg/produksi'
      preLoaderRoute: typeof SppgProduksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sppg/pengiriman': {
      id: '/sppg/pengiriman'
      path: '/sppg/pengiriman'
      fullPath: '/sppg/pengiriman'
      preLoaderRoute: typeof SppgPengirimanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sppg/keuangan': {
      id: '/sppg/keuangan'
      path: '/sppg/keuangan'
      fullPath: '/sppg/keuangan'
      preLoaderRoute: typeof SppgKeuanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$token': {
      id: '/register/$token'
      path: '/register/$token'
      fullPath: '/register/$token'
      preLoaderRoute: typeof RegisterTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  DataRoute: DataRoute,
  DriverRoute: DriverRoute,
  LoginRoute: LoginRoute,
  RegisterTokenRoute: RegisterTokenRoute,
  SppgKeuanganRoute: SppgKeuanganRoute,
  SppgPengirimanRoute: SppgPengirimanRoute,
  SppgProduksiRoute: SppgProduksiRoute,
  SppgProfilRoute: SppgProfilRoute,
  SppgIndexRoute: SppgIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
