/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PedaganglokalRouteImport } from './routes/pedaganglokal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DataRouteImport } from './routes/data'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SppgIndexRouteImport } from './routes/sppg/index'
import { Route as SekolahIndexRouteImport } from './routes/sekolah/index'
import { Route as SppgProfilRouteImport } from './routes/sppg/profil'
import { Route as SppgProduksiRouteImport } from './routes/sppg/produksi'
import { Route as SppgPengirimanRouteImport } from './routes/sppg/pengiriman'
import { Route as SppgKeuanganRouteImport } from './routes/sppg/keuangan'
import { Route as SekolahPesertadidikRouteImport } from './routes/sekolah/pesertadidik'
import { Route as SekolahGiziRouteImport } from './routes/sekolah/gizi'
import { Route as RegisterTokenRouteImport } from './routes/register/$token'
import { Route as PosyanduGiziRouteImport } from './routes/posyandu/gizi'
import { Route as PosyanduBusuiRouteImport } from './routes/posyandu/busui'
import { Route as PosyanduBumilRouteImport } from './routes/posyandu/bumil'
import { Route as PosyanduBalitaRouteImport } from './routes/posyandu/balita'

const PedaganglokalRoute = PedaganglokalRouteImport.update({
  id: '/pedaganglokal',
  path: '/pedaganglokal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SppgIndexRoute = SppgIndexRouteImport.update({
  id: '/sppg/',
  path: '/sppg/',
  getParentRoute: () => rootRouteImport,
} as any)
const SekolahIndexRoute = SekolahIndexRouteImport.update({
  id: '/sekolah/',
  path: '/sekolah/',
  getParentRoute: () => rootRouteImport,
} as any)
const SppgProfilRoute = SppgProfilRouteImport.update({
  id: '/sppg/profil',
  path: '/sppg/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SppgProduksiRoute = SppgProduksiRouteImport.update({
  id: '/sppg/produksi',
  path: '/sppg/produksi',
  getParentRoute: () => rootRouteImport,
} as any)
const SppgPengirimanRoute = SppgPengirimanRouteImport.update({
  id: '/sppg/pengiriman',
  path: '/sppg/pengiriman',
  getParentRoute: () => rootRouteImport,
} as any)
const SppgKeuanganRoute = SppgKeuanganRouteImport.update({
  id: '/sppg/keuangan',
  path: '/sppg/keuangan',
  getParentRoute: () => rootRouteImport,
} as any)
const SekolahPesertadidikRoute = SekolahPesertadidikRouteImport.update({
  id: '/sekolah/pesertadidik',
  path: '/sekolah/pesertadidik',
  getParentRoute: () => rootRouteImport,
} as any)
const SekolahGiziRoute = SekolahGiziRouteImport.update({
  id: '/sekolah/gizi',
  path: '/sekolah/gizi',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTokenRoute = RegisterTokenRouteImport.update({
  id: '/register/$token',
  path: '/register/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PosyanduGiziRoute = PosyanduGiziRouteImport.update({
  id: '/posyandu/gizi',
  path: '/posyandu/gizi',
  getParentRoute: () => rootRouteImport,
} as any)
const PosyanduBusuiRoute = PosyanduBusuiRouteImport.update({
  id: '/posyandu/busui',
  path: '/posyandu/busui',
  getParentRoute: () => rootRouteImport,
} as any)
const PosyanduBumilRoute = PosyanduBumilRouteImport.update({
  id: '/posyandu/bumil',
  path: '/posyandu/bumil',
  getParentRoute: () => rootRouteImport,
} as any)
const PosyanduBalitaRoute = PosyanduBalitaRouteImport.update({
  id: '/posyandu/balita',
  path: '/posyandu/balita',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/driver': typeof DriverRoute
  '/login': typeof LoginRoute
  '/pedaganglokal': typeof PedaganglokalRoute
  '/posyandu/balita': typeof PosyanduBalitaRoute
  '/posyandu/bumil': typeof PosyanduBumilRoute
  '/posyandu/busui': typeof PosyanduBusuiRoute
  '/posyandu/gizi': typeof PosyanduGiziRoute
  '/register/$token': typeof RegisterTokenRoute
  '/sekolah/gizi': typeof SekolahGiziRoute
  '/sekolah/pesertadidik': typeof SekolahPesertadidikRoute
  '/sppg/keuangan': typeof SppgKeuanganRoute
  '/sppg/pengiriman': typeof SppgPengirimanRoute
  '/sppg/produksi': typeof SppgProduksiRoute
  '/sppg/profil': typeof SppgProfilRoute
  '/sekolah/': typeof SekolahIndexRoute
  '/sppg/': typeof SppgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/driver': typeof DriverRoute
  '/login': typeof LoginRoute
  '/pedaganglokal': typeof PedaganglokalRoute
  '/posyandu/balita': typeof PosyanduBalitaRoute
  '/posyandu/bumil': typeof PosyanduBumilRoute
  '/posyandu/busui': typeof PosyanduBusuiRoute
  '/posyandu/gizi': typeof PosyanduGiziRoute
  '/register/$token': typeof RegisterTokenRoute
  '/sekolah/gizi': typeof SekolahGiziRoute
  '/sekolah/pesertadidik': typeof SekolahPesertadidikRoute
  '/sppg/keuangan': typeof SppgKeuanganRoute
  '/sppg/pengiriman': typeof SppgPengirimanRoute
  '/sppg/produksi': typeof SppgProduksiRoute
  '/sppg/profil': typeof SppgProfilRoute
  '/sekolah': typeof SekolahIndexRoute
  '/sppg': typeof SppgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/driver': typeof DriverRoute
  '/login': typeof LoginRoute
  '/pedaganglokal': typeof PedaganglokalRoute
  '/posyandu/balita': typeof PosyanduBalitaRoute
  '/posyandu/bumil': typeof PosyanduBumilRoute
  '/posyandu/busui': typeof PosyanduBusuiRoute
  '/posyandu/gizi': typeof PosyanduGiziRoute
  '/register/$token': typeof RegisterTokenRoute
  '/sekolah/gizi': typeof SekolahGiziRoute
  '/sekolah/pesertadidik': typeof SekolahPesertadidikRoute
  '/sppg/keuangan': typeof SppgKeuanganRoute
  '/sppg/pengiriman': typeof SppgPengirimanRoute
  '/sppg/produksi': typeof SppgProduksiRoute
  '/sppg/profil': typeof SppgProfilRoute
  '/sekolah/': typeof SekolahIndexRoute
  '/sppg/': typeof SppgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/data'
    | '/driver'
    | '/login'
    | '/pedaganglokal'
    | '/posyandu/balita'
    | '/posyandu/bumil'
    | '/posyandu/busui'
    | '/posyandu/gizi'
    | '/register/$token'
    | '/sekolah/gizi'
    | '/sekolah/pesertadidik'
    | '/sppg/keuangan'
    | '/sppg/pengiriman'
    | '/sppg/produksi'
    | '/sppg/profil'
    | '/sekolah/'
    | '/sppg/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/data'
    | '/driver'
    | '/login'
    | '/pedaganglokal'
    | '/posyandu/balita'
    | '/posyandu/bumil'
    | '/posyandu/busui'
    | '/posyandu/gizi'
    | '/register/$token'
    | '/sekolah/gizi'
    | '/sekolah/pesertadidik'
    | '/sppg/keuangan'
    | '/sppg/pengiriman'
    | '/sppg/produksi'
    | '/sppg/profil'
    | '/sekolah'
    | '/sppg'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/data'
    | '/driver'
    | '/login'
    | '/pedaganglokal'
    | '/posyandu/balita'
    | '/posyandu/bumil'
    | '/posyandu/busui'
    | '/posyandu/gizi'
    | '/register/$token'
    | '/sekolah/gizi'
    | '/sekolah/pesertadidik'
    | '/sppg/keuangan'
    | '/sppg/pengiriman'
    | '/sppg/produksi'
    | '/sppg/profil'
    | '/sekolah/'
    | '/sppg/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  DataRoute: typeof DataRoute
  DriverRoute: typeof DriverRoute
  LoginRoute: typeof LoginRoute
  PedaganglokalRoute: typeof PedaganglokalRoute
  PosyanduBalitaRoute: typeof PosyanduBalitaRoute
  PosyanduBumilRoute: typeof PosyanduBumilRoute
  PosyanduBusuiRoute: typeof PosyanduBusuiRoute
  PosyanduGiziRoute: typeof PosyanduGiziRoute
  RegisterTokenRoute: typeof RegisterTokenRoute
  SekolahGiziRoute: typeof SekolahGiziRoute
  SekolahPesertadidikRoute: typeof SekolahPesertadidikRoute
  SppgKeuanganRoute: typeof SppgKeuanganRoute
  SppgPengirimanRoute: typeof SppgPengirimanRoute
  SppgProduksiRoute: typeof SppgProduksiRoute
  SppgProfilRoute: typeof SppgProfilRoute
  SekolahIndexRoute: typeof SekolahIndexRoute
  SppgIndexRoute: typeof SppgIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pedaganglokal': {
      id: '/pedaganglokal'
      path: '/pedaganglokal'
      fullPath: '/pedaganglokal'
      preLoaderRoute: typeof PedaganglokalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sppg/': {
      id: '/sppg/'
      path: '/sppg'
      fullPath: '/sppg/'
      preLoaderRoute: typeof SppgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sekolah/': {
      id: '/sekolah/'
      path: '/sekolah'
      fullPath: '/sekolah/'
      preLoaderRoute: typeof SekolahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sppg/profil': {
      id: '/sppg/profil'
      path: '/sppg/profil'
      fullPath: '/sppg/profil'
      preLoaderRoute: typeof SppgProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sppg/produksi': {
      id: '/sppg/produksi'
      path: '/sppg/produksi'
      fullPath: '/sppg/produksi'
      preLoaderRoute: typeof SppgProduksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sppg/pengiriman': {
      id: '/sppg/pengiriman'
      path: '/sppg/pengiriman'
      fullPath: '/sppg/pengiriman'
      preLoaderRoute: typeof SppgPengirimanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sppg/keuangan': {
      id: '/sppg/keuangan'
      path: '/sppg/keuangan'
      fullPath: '/sppg/keuangan'
      preLoaderRoute: typeof SppgKeuanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sekolah/pesertadidik': {
      id: '/sekolah/pesertadidik'
      path: '/sekolah/pesertadidik'
      fullPath: '/sekolah/pesertadidik'
      preLoaderRoute: typeof SekolahPesertadidikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sekolah/gizi': {
      id: '/sekolah/gizi'
      path: '/sekolah/gizi'
      fullPath: '/sekolah/gizi'
      preLoaderRoute: typeof SekolahGiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$token': {
      id: '/register/$token'
      path: '/register/$token'
      fullPath: '/register/$token'
      preLoaderRoute: typeof RegisterTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posyandu/gizi': {
      id: '/posyandu/gizi'
      path: '/posyandu/gizi'
      fullPath: '/posyandu/gizi'
      preLoaderRoute: typeof PosyanduGiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posyandu/busui': {
      id: '/posyandu/busui'
      path: '/posyandu/busui'
      fullPath: '/posyandu/busui'
      preLoaderRoute: typeof PosyanduBusuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posyandu/bumil': {
      id: '/posyandu/bumil'
      path: '/posyandu/bumil'
      fullPath: '/posyandu/bumil'
      preLoaderRoute: typeof PosyanduBumilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posyandu/balita': {
      id: '/posyandu/balita'
      path: '/posyandu/balita'
      fullPath: '/posyandu/balita'
      preLoaderRoute: typeof PosyanduBalitaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  DataRoute: DataRoute,
  DriverRoute: DriverRoute,
  LoginRoute: LoginRoute,
  PedaganglokalRoute: PedaganglokalRoute,
  PosyanduBalitaRoute: PosyanduBalitaRoute,
  PosyanduBumilRoute: PosyanduBumilRoute,
  PosyanduBusuiRoute: PosyanduBusuiRoute,
  PosyanduGiziRoute: PosyanduGiziRoute,
  RegisterTokenRoute: RegisterTokenRoute,
  SekolahGiziRoute: SekolahGiziRoute,
  SekolahPesertadidikRoute: SekolahPesertadidikRoute,
  SppgKeuanganRoute: SppgKeuanganRoute,
  SppgPengirimanRoute: SppgPengirimanRoute,
  SppgProduksiRoute: SppgProduksiRoute,
  SppgProfilRoute: SppgProfilRoute,
  SekolahIndexRoute: SekolahIndexRoute,
  SppgIndexRoute: SppgIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
